Card 부분 기능 추가
prography/correctcode-front pull request #16
Opened 2019-11-28 06:37 UTC by illlama

reviewer / reviewee 따라 그리고 status에 따라 분류
-status는 pending, ongoing, completed 로 분류
사진, userId, language 아직 추가 못함 <- 서버에서 받아와야
시간 부분 아직 기능 구현 안했습니다.
homepage 브랜치로 혼동 드려서 죄송합니다.

2019-11-28 06:39 UTC, geusan commented
userId 가 어디서 주는걸 말하는거야?

2019-11-28 06:39 UTC, geusan commented
사진은 로그인 다시 한번 해줘

2019-11-28 06:41 UTC, geusan commented
repository 목록에서는 language를 줄건데, 지금은 language: unknown으로 통일되있어

2019-11-28 13:07 UTC, Godsenal requested changes
고생하셨슴당

2019-11-28 13:07 UTC, Godsenal commented on src/components/Card.tsx
> +  const CommonCard = () => {
이거 이렇게 함수형 컴포넌트 안에 함수를 다시선언하면 랜더될때마다 함수가 생성돼
컴포넌트를 굳이 이렇게 안에 넣을 필요없고, 밖에다 빼주삼

2019-11-28 13:07 UTC, Godsenal commented on src/components/Card.tsx
> +    } else {
굳이 else 쓸 필요없을듯

2019-11-28 13:07 UTC, Godsenal commented on src/components/CardList.tsx
> +        <Card key={review.id} review={review} userType={userType} />
이렇게 userType을 카드컴포넌트에 props로 넘겨주고 Card 컴포넌트에서 분기쳐주면 카드가 100개라고 치면 카드안에서 100번 분기되잖아?
이럴 경우에는 CardList에서 userType에 따라 랜더해줄 컴포넌트를 정하고 그 컴포넌트를 랜더하는게 맞을것같음

2019-11-29 06:50 UTC, illlama commented on src/components/CardList.tsx
> +        <Card key={review.id} review={review} userType={userType} />
이 부분 나눠서 새로 커밋했는데
리뷰어/리뷰이로 나눴기 때문에 기존에 있던 Card.tsx는 일단 지우진 않았습니다..

2019-11-29 07:47 UTC, closed without merging