Card 리뷰 반영
prography/correctcode-front pull request #17
Opened 2019-11-29 07:54 UTC by illlama

- 리뷰어카드/리뷰이카드로 나눔 -> Card.tsx는 혹시 몰라 그대로 놔뒀습니다
- 컴포넌트 내의 함수들 꺼냄
- 카드 기능 구현했지만 아직 이미지 파일이나 유저 내임이 빈 공간이라 깨집니다

아까 올렸다가 뭐 잘못올려서 되돌리다 풀리퀘 다 날려서 다시 올려요...

2019-12-01 13:32 UTC, Godsenal requested changes
수고하셧슴당

2019-12-01 13:32 UTC, Godsenal commented on src/components/Card.tsx
> +  userType: string;
model에 있는 `UserType ` 쓰면될듯

2019-12-01 13:32 UTC, Godsenal commented on src/components/Card.tsx
> +  if (userType === 'reviewer') {
여기도 `UserType`

2019-12-03 02:14 UTC, illlama commented on src/pages/DashReviewee.tsx
> +  const reviews = useSelector((state: StoreState) => state.review.reviews);
userReviews가 아니라 reviews가 reviewee로 접속했을때 리뷰들받아오는 거였어서 수정함

2019-12-03 07:20 UTC, Godsenal commented
LGTM
차근차근 같이 구조를 바꿔봅시다

2019-12-03 07:21 UTC, Godsenal approved these changes

2019-12-06 14:22 UTC, merged